# Generated by Django 6.0.6 on 2026-06-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_days', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('pickup', 'Retiro en Local'), ('delivery', 'Envío Local (Uber)'), ('national', 'Envío Nacional')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['type', 'price'],
            },
        ),
    ]
