# Generated by Django 6.1 on 2026-09-22 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=50)),
                ('shipping_address', models.TextField(blank=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('delivered', 'Entregado'), ('payment_rejected', 'Pago rechazado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('mercado_pago', ' Mercado Pago'), ('efectivo', 'Efectivo')], default='mercado_pago', max_length=20)),
                ('mercadopago_preference_id', models.CharField(blank=True, default='', max_length=100)),
                ('mercadopago_payment_id', models.CharField(blank=True, default='', max_length=100)),
                ('stock_deducted', models.BooleanField(default=False)),
                ('shipping_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.shippingoption')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
