# Generated by Django 6.0.6 on 2026-08-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_session_id_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mercadopago_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='mercadopago_preference_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mercado_pago', ' Mercado Pago'), ('efectivo', 'Efectivo')], default='mercado_pago', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('payment_rejected', 'Pago rechazado'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('entregado', 'Entregado')], default='pending', max_length=20),
        ),
    ]
