# Generated by Django 6.1 on 2026-09-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='vip_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio especial para clientes frecuentes. Dejar vacío si no aplica descuento.', max_digits=10, null=True),
        ),
    ]
