# Generated by Django 6.1 on 2026-09-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_variant_vip_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='base_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='price',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='vip_price',
        ),
        migrations.AddField(
            model_name='product',
            name='vip_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio especial para clientes frecuentes. Dejar vacío si no aplica descuento.', max_digits=10, null=True),
        ),
    ]
